7.6.1 = https://github.com/Bearsampp/modules-untouched/releases/download/powershell-2026.4.24/PowerShell-7.6.1-win-x64.zip
7.6.0 = https://github.com/Bearsampp/modules-untouched/releases/download/powershell-2026.3.22/PowerShell-7.6.0-win-x64.zip
7.5.4 = https://github.com/Bearsampp/modules-untouched/releases/download/powershell-2025.11.30/PowerShell-7.5.4-win-x64.zip
